### ISSUE TITLE
Can't launch training (accelerate error)

### ISSUE THREAD

**Issue by Hezow** [monsterhunters/Lora-Training-GUI#4]
### My config 
```
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "no"
enable_bucket = true
epoch = 10
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
keep_tokens = 1
logging_dir = "/content/drive/MyDrive/Lora-1/log"
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 3
lr_scheduler_power = 1
lr_warmup_steps = 0.05
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 0.75
max_timestep = 1000
max_token_length = 150
max_train_steps = 1960
min_bucket_reso = 256
min_snr_gamma = 8
mixed_precision = "fp16"
network_alpha = 4
network_args = [ "rank_dropout=0.2", "module_dropout=0.2",]
network_dim = 8
network_dropout = 0.55
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = [ "weight_decay=0.1", "betas=[0.9,0.99]",]
optimizer_type = "AdamW8bit"
output_dir = "/content/drive/MyDrive/Lora-1/model"
output_name = "PynPyn-syl"
pretrained_model_name_or_path = "/content/Model/T-illunai3.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "/content/drive/MyDrive/Lora-1/model/sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
scale_weight_norms = 0.9
shuffle_caption = true
text_encoder_lr = [ 6e-5, 6e-5,]
train_batch_size = 2
train_data_dir = "/content/drive/MyDrive/Lora-1/img"
unet_lr = 0.0003
wandb_run_name = "PynPyn-syl"
xformers = true
```

### The output
```
        SDXL学習ではclip_skipは動作しません                                    
                    INFO     preparing accelerator                              train_network.py:404
                    INFO     loading model for process 0/1                     sdxl_train_util.py:32
                    INFO     load StableDiffusion checkpoint:                  sdxl_train_util.py:73
                             /content/Model/T-illunai3.safetensors                                  
2024-12-16 18:13:33 INFO     building U-Net                                   sdxl_model_util.py:198
2024-12-16 18:13:34 INFO     loading U-Net from checkpoint                    sdxl_model_util.py:202
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', '/content/drive/MyDrive/Lora-1/model/config_lora-20241216-181314.toml']' died with <Signals.SIGKILL: 9>.
18:14:06-443849 INFO     Training has ended.
```

**Comment by Hezow** [comment]
Oh it's a RAM issue, Lowvram parametter "Enable low RAM optimization. e.g. load models to VRAM instead of RAM (for machines which have bigger VRAM than RAM such as Colab and Kaggle)" doesn't work ?

**Comment by monsterhunters** [comment]
Hi @Hezow , I think SDXL or upper model are not working due to low ram. In that case, we need to load diffuser model instead of safetensor. But ,at the moment, GUI not supporting diffuser model yet. If you found somewhere which support SDXL on gui, please let me know.
